SUPABASE_URL = "https://wdrwqqpbilxtucyuitde.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkcndxcXBiaWx4dHVjeXVpdGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MDgyMzcsImV4cCI6MjA2MTM4NDIzN30.QPmmsaH0idohpEaHD9ElXqEJp9Eo47tXo0fzStIhJzc"
